# Generated by Django 4.1 on 2022-12-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', models.TextField()),
                ('update', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
