# Generated by Django 4.1 on 2023-01-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('title', models.CharField(help_text='Enter name', max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Enter description')),
                ('id', models.CharField(help_text='Enter product code', max_length=5, primary_key=True, serialize=False)),
            ],
        ),
    ]
