# Generated by Django 4.1 on 2023-01-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='topic',
            field=models.TextField(choices=[('laptop', 'laptop'), ('desktop', 'desktop')], default='------'),
        ),
    ]
