# Generated by Django 4.1 on 2023-01-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_goods_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='topic',
            field=models.TextField(choices=[('laptop', 'laptop'), ('desktop', 'desktop')]),
        ),
    ]
